name: Build and Deploy to Netlify
on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run Tests
        run: echo "dont have test for web app..."

  deploy-dev:
    needs: test
    name: "Deploy web to Vercel dev"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Publish
        uses: netlify/actions/build@master
        env:
          # NETLIFY_BASE: site
          NETLIFY_CMD: npm build
          # NETLIFY_DIR: site/web
          REACT_APP_BACKEND_BASE_URL: https://backend-blop-p.vercel.app/
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
# jobs:
#   build:
#     name: deploy-netifly
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       # ( Build to ./dist or other directory... )

#       - name: Deploy to Netlify
#         uses: nwtgck/actions-netlify@v1.2
#       - name: install && build
#         run: |
#           npm install
#           npm run build
#         with:
#           publish-dir: "./dist/frontend"
#           production-branch: staging
#           deploy-message: "Deploy from GitHub Actions"
#           enable-pull-request-comment: false
#           enable-commit-comment: true
#           overwrites-pull-request-comment: true
#         env:
#           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
#           NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
#         timeout-minutes: 1
